/* tslint:disable */
require("./IssuedDocuments.module.css");
const styles = {
  container: 'container_b02ae57e',
  libraryRow: 'libraryRow_b02ae57e',
  librarySelector: 'librarySelector_b02ae57e',
  dropdownLoading: 'dropdownLoading_b02ae57e',
  hyperLink: 'hyperLink_b02ae57e',
  searchContainer: 'searchContainer_b02ae57e',
  searchIcon: 'searchIcon_b02ae57e',
  inputWrapper: 'inputWrapper_b02ae57e',
  searchInput: 'searchInput_b02ae57e',
  clearIcon: 'clearIcon_b02ae57e',
  loading: 'loading_b02ae57e',
  contentBody: 'contentBody_b02ae57e',
  contentBodyInner: 'contentBodyInner_b02ae57e',
  sidebar: 'sidebar_b02ae57e',
  folderHeader: 'folderHeader_b02ae57e',
  folderIcon: 'folderIcon_b02ae57e',
  folderList: 'folderList_b02ae57e',
  folderWrapper: 'folderWrapper_b02ae57e',
  folderItem: 'folderItem_b02ae57e',
  selected: 'selected_b02ae57e',
  folderContent: 'folderContent_b02ae57e',
  folderName: 'folderName_b02ae57e',
  chevron: 'chevron_b02ae57e',
  subFolderList: 'subFolderList_b02ae57e',
  fileList: 'fileList_b02ae57e',
  fileHeader: 'fileHeader_b02ae57e',
  sortButton: 'sortButton_b02ae57e',
  documentItem: 'documentItem_b02ae57e',
  fileType: 'fileType_b02ae57e',
  fileTitle: 'fileTitle_b02ae57e',
  fileTitleRow: 'fileTitleRow_b02ae57e',
  fileName: 'fileName_b02ae57e',
  status: 'status_b02ae57e',
  views: 'views_b02ae57e',
  fileMeta: 'fileMeta_b02ae57e',
  metaItem: 'metaItem_b02ae57e',
  metaIcon: 'metaIcon_b02ae57e',
  fileContent: 'fileContent_b02ae57e',
  backButton: 'backButton_b02ae57e',
  pagination: 'pagination_b02ae57e',
  iconFolders: 'iconFolders_b02ae57e',
  errorMessage: 'errorMessage_b02ae57e',
  loadingContainer: 'loadingContainer_b02ae57e',
  searchButton: 'searchButton_b02ae57e',
  loadingSpinner: 'loadingSpinner_b02ae57e',
  spinner: 'spinner_b02ae57e',
  spin: 'spin_b02ae57e'
};

export default styles;
/* tslint:enable */